[build]
builder = "nixpacks"
buildCommand = "npm install --prefix server && npm install --prefix client && VITE_API_URL=/api npm run build --prefix client"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
